FTP server (+ UI)
Krock21rus/hwproj_tasks pull request #1
Opened 2019-06-02 15:15 UTC by 123a6bcw

2019-06-05 01:09 UTC, 123a6bcw commented
1) "Давайте сделаем в стиле Far manager, Юрий Викторович наверняка оценит".
Белым цветом обозначены папки, серым -- файлы. Перемещение W/UP, S/DOWN, ENTER на папке -- открыть папку, на файле -- скачать файл.
2) У нас нет тестов на работу сервера/клиента потому, что ~~уже влом~~ я постарался протестировать всю нужную логику в ЮаЙ ТеСтАх.

2019-06-05 01:26 UTC, 123a6bcw commented
3. А, там ещё есть помойный FXML -- я просто не въехал, что для тестирования в testfx можно просто выставлять id через .setId();

2019-06-05 04:38 UTC, 123a6bcw commented
4. Ок, на всякий случай добавил ещё тест (не UI), который проверяет, что сервер может работать с несколькими чуваками.

2019-06-05 05:00 UTC, 123a6bcw commented
5. Не снимайте баллы за неумение работать с гитом плз -- работа начиналась с работы на паре (поэтому там были коммиты в мастер и отсутствие сообщений), пришлось фиксить.

2019-06-05 06:43 UTC, 123a6bcw commented
6. Не сворачивайтесь, если будете запускать тесты, иначе там всё падает.

2019-06-07 08:00 UTC, yurii-litvinov requested changes
- Совсем нет CI
- Я бы не просил у пользователя порт, раз он 4242, или хотя бы предлагал значение по умолчанию

А вообще, очень круто

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/Client.java
> +            // waiting
Крутящееся ожидание нехорошо, хотя бы Thread.sleep на небольшое время было бы лучше

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/FileDescription.java
> +public class FileDescription {
Хорошее место для применения Lombok. Но дело вкуса :)

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/GUI/ClientUIController.java
> +        });
Я бы это вынес в отдельный метод

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/GUI/ClientUIController.java
> +            labels[i].setFont(Font.font(fileHeight/1.5));
Пробела не хватает :)

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/Server.java
> +        Server server = new Server(pathToDir);
var

2019-06-07 08:00 UTC, yurii-litvinov commented on task4/src/test/java/me/hwproj/ClientTest.java
> +    void tearDown () {
Лишний пробел :)

2019-06-07 15:38 UTC, 123a6bcw commented
CI уже не получится добавить(.

2019-06-09 12:15 UTC, 123a6bcw commented
Обманул, кста, добавил CI.

2019-06-09 18:28 UTC, yurii-litvinov approved these changes
CI не вынес такого количества UI-тестов и сдох. Но сами по себе UI-тесты --- это круто, так что пусть так и будет (хотя можно было поковырять настройки gradle, чтобы он в лог не спамил). Ок, зачтена.

2019-06-09 18:28 UTC, yurii-litvinov commented on task4/src/main/java/me/hwproj/GUI/ClientUIController.java
> +                }
Я бы и это в отдельный метод вынес, раз пошло такое дело

2020-02-26 11:43 UTC, closed without merging